
- name: update repositories cache
  apt:
     update_cache: yes

- name: install dependencies
  apt:
     name: "{{ packages }}"
  vars:
     packages:
      - apache2
      - mysql-server
      - php
      - php-mysql
      - libapache2-mod-php
      - php-xml
      - php-mbstring
      - php-apcu
      - php-intl
      - imagemagick
      - inkscape
      - php-gd
      - php-cli
      - php-curl
      - git
      - python-mysqldb

- name: create mediawiki directory
  file:
    path: /var/lib/mediawiki
    state: directory

- name: download and unpack mediawiki
  unarchive:
    src: https://releases.wikimedia.org/mediawiki/1.32/mediawiki-1.32.0.tar.gz
    dest: /var/lib/mediawiki
    remote_src: yes

- name: create mediawiki database
  mysql_db:
    name: my_wiki
    state: present

- mysql_user:
    name: "{{ media_wiki_user }}"
    host: localhost
    password: "{{ media_wiki_password }}"
    priv: 'my_wiki.*:ALL'
    state: present

- file:
    src: '{{ item.src }}'
    dest: '/var/www/html/{{ item.dest }}'
    state: link
  with_items:
    - { src: '/var/lib/mediawiki', dest: 'mediawiki' }
    - { src: '/var/www/html/mediawiki/mediawiki-1.32.0/index.php', dest: 'index.php' }

- name: replacing apache's virtual host
  copy:
    src: source_code/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf

- name: copy the hope matter's logo
  copy:
    src: source_code/hope_matters_logo.png
    dest: /var/www/html/mediawiki/mediawiki-1.32.0/hope_matters_logo.png

- template:
    src: source_code/LocalSettings.php
    dest: /var/www/html/mediawiki/mediawiki-1.32.0/LocalSettings.php

- name: reload apache
  service:
    name: apache2
    state: reloaded
